// Generated by scripts/build-sprites.mjs from design/sprites.json. Do not edit by hand.
export const PALETTE = {
  "H": "#b6c0c6",
  "G": "#87939e",
  "g": "#576571",
  "B": "#a77849",
  "b": "#714c32",
  "Y": "#f7cc32",
  "y": "#ffe99a",
  "U": "#dfa927",
  "W": "#bd8826",
  "S": "#895e24",
  "O": "#ed8c36",
  "o": "#a85e30",
  "K": "#252b35",
  "w": "#fff9dc",
  "D": "#b7bbb8",
  "E": "#d5d7cf",
  "d": "#828b8e",
  "s": "#59636c",
  "x": "#303742",
  "t": "#979184"
}

export const SPRITES = {
  "normal": {
    "width": 20,
    "height": 12,
    "frames": {
      "idle": [
        ".........HG.........",
        "......HHH..GGG......",
        "....HH........GG....",
        "..HG.g....WWW...GG..",
        ".G...g...WYyYYW.g.G.",
        ".G...g...WYYwKYOg.G.",
        ".G...g.WUWWYyyW.g.G.",
        ".G...SWWSSWYyyW.g.G.",
        ".G.SWg...WUYyW..g.G.",
        ".GbBBBBBBBOBBOBBBbG.",
        "GG...g..........g.GG",
        ".gGGGGggggggggggggg."
      ],
      "blink": [
        ".........HG.........",
        "......HHH..GGG......",
        "....HH........GG....",
        "..HG.g....WWW...GG..",
        ".G...g...WYyYYW.g.G.",
        ".G...g...WYYKKYOg.G.",
        ".G...g.WUWWYyyW.g.G.",
        ".G...SWWSSWYyyW.g.G.",
        ".G.SWg...WUYyW..g.G.",
        ".GbBBBBBBBOBBOBBBbG.",
        "GG...g..........g.GG",
        ".gGGGGggggggggggggg."
      ],
      "chirp": [
        ".........HG.........",
        "......HHH..GGG......",
        "....HH........GG....",
        "..HG.g....WWW...GG..",
        ".G...g...WYyYYWOg.G.",
        ".G...g...WYYwKYKg.G.",
        ".G...g.WUWWYyyWOg.G.",
        ".G...SWWSSWYyyW.g.G.",
        ".G.SWg...WUYyW..g.G.",
        ".GbBBBBBBBOBBOBBBbG.",
        "GG...g..........g.GG",
        ".gGGGGggggggggggggg."
      ],
      "hop": [
        ".........HG.........",
        "......HHH..GGG......",
        "....HH....WWW.GG....",
        "..HG.g...WYyYYW.GG..",
        ".G...g...WYYwKYOg.G.",
        ".G...g.WUWWYyyW.g.G.",
        ".G...SWWSSWYyyW.g.G.",
        ".G.SWg...WUYyW..g.G.",
        ".G...g....o.o...g.G.",
        ".GbBBBBBBBBBBBBBBbG.",
        "GG...g..........g.GG",
        ".gGGGGggggggggggggg."
      ],
      "dead": [
        ".........HG.........",
        "......HHH..GGG......",
        "....HH........GG....",
        "..HG.g..........GG..",
        ".GbBBBBBBBBBBBBBBbG.",
        ".G...g..........g.G.",
        ".G...g.o.o......g.G.",
        ".G...g.o.o..dEd.g.G.",
        ".G...dEEEEDExExDg.G.",
        ".G.sdDdddDDDDxEDo.G.",
        "GG..ssdDDDsDxExDg.GG",
        ".gGGGGggggggggggggg."
      ]
    }
  },
  "large": {
    "width": 24,
    "height": 16,
    "frames": {
      "idle": [
        "...........HG...........",
        "..........H..G..........",
        "........HHHHGGGG........",
        "......HH........GG......",
        "....HH..g...WWWg..GG....",
        "...H...g...WYyYYW...G...",
        "..G....g...WYYwKYO...G..",
        "..G....g..WYYyyYW....G..",
        "..G....gWUWWYyyYW....G..",
        "..G....SWWUWYyyWg....G..",
        "..G..SWWSSWUYYW.g....G..",
        "..G.SW.g...o..o.g....G..",
        "..GbBBBBBBoOBoOBBBBBbG..",
        "..G....g...g....g....G..",
        ".GHHHHHHGGGGGGGGGGGGGGG.",
        "..gggggggggggggggggggg.."
      ],
      "blink": [
        "...........HG...........",
        "..........H..G..........",
        "........HHHHGGGG........",
        "......HH........GG......",
        "....HH..g...WWWg..GG....",
        "...H...g...WYyYYW...G...",
        "..G....g...WYYKKYO...G..",
        "..G....g..WYYyyYW....G..",
        "..G....gWUWWYyyYW....G..",
        "..G....SWWUWYyyWg....G..",
        "..G..SWWSSWUYYW.g....G..",
        "..G.SW.g...o..o.g....G..",
        "..GbBBBBBBoOBoOBBBBBbG..",
        "..G....g...g....g....G..",
        ".GHHHHHHGGGGGGGGGGGGGGG.",
        "..gggggggggggggggggggg.."
      ],
      "chirp": [
        "...........HG...........",
        "..........H..G..........",
        "........HHHHGGGG........",
        "......HH........GG......",
        "....HH..g...WWWg..GG....",
        "...H...g...WYyYYWO..G...",
        "..G....g...WYYwKYK...G..",
        "..G....g..WYYyyYWO...G..",
        "..G....gWUWWYyyYW....G..",
        "..G....SWWUWYyyWg....G..",
        "..G..SWWSSWUYYW.g....G..",
        "..G.SW.g...o..o.g....G..",
        "..GbBBBBBBoOBoOBBBBBbG..",
        "..G....g...g....g....G..",
        ".GHHHHHHGGGGGGGGGGGGGGG.",
        "..gggggggggggggggggggg.."
      ],
      "hop": [
        "...........HG...........",
        "..........H..G..........",
        "........HHHHGGGG........",
        "......HH....WWW.GG......",
        "....HH..g..WYyYYW.GG....",
        "...H...g...WYYwKYO..G...",
        "..G....g..WYYyyYW....G..",
        "..G....gWUWWYyyYW....G..",
        "..G....SWWUWYyyWg....G..",
        "..G..SWWSSWUYYW.g....G..",
        "..G.SW.g..oO.oO.g....G..",
        "..G....g...g....g....G..",
        "..GbBBBBBBBBBBBBBBBBbG..",
        "..G....g...g....g....G..",
        ".GHHHHHHGGGGGGGGGGGGGGG.",
        "..gggggggggggggggggggg.."
      ],
      "dead": [
        "...........HG...........",
        "..........H..G..........",
        "........HHHHGGGG........",
        "......HH........GG......",
        "....HH..g......g..GG....",
        "...H...g...g....g...G...",
        "..GbBBBBBBBBBBBBBBBBbG..",
        "..G....g...g....g....G..",
        "..G....go..o....g....G..",
        "..G....go..o...dEd...G..",
        "..G....dEEEEDDExExD..G..",
        "..G.sdDDEdddDDDExEDo.G..",
        "..G..sdDDdddDDExExD..G..",
        "..G....sdDDDDdsddd...G..",
        ".GHHHHHHGGGGGGGGGGGGGGG.",
        "..gggggggggggggggggggg.."
      ]
    }
  },
  "small": {
    "width": 14,
    "height": 8,
    "frames": {
      "idle": [
        ".....HHGG.....",
        "..HHH....GGG..",
        ".H....WYY...G.",
        "G.g...YwKYOg.G",
        "G.g.WUYYyW.g.G",
        "G.gSWWUyy..g.G",
        "G.g...o.o..g.G",
        "gHHHGGGGGGGGgg"
      ],
      "blink": [
        ".....HHGG.....",
        "..HHH....GGG..",
        ".H....WYY...G.",
        "G.g...YKKYOg.G",
        "G.g.WUYYyW.g.G",
        "G.gSWWUyy..g.G",
        "G.g...o.o..g.G",
        "gHHHGGGGGGGGgg"
      ],
      "chirp": [
        ".....HHGG.....",
        "..HHH....GGG..",
        ".H....WYY.O.G.",
        "G.g...YwKYKg.G",
        "G.g.WUYYyWOg.G",
        "G.gSWWUyy..g.G",
        "G.g...o.o..g.G",
        "gHHHGGGGGGGGgg"
      ],
      "hop": [
        ".....HHGG.....",
        "..HHH.WYYGGG..",
        ".H....YwKYO.G.",
        "G.g.WUYYyW.g.G",
        "G.gSWWUyy..g.G",
        "G.g...o.o..g.G",
        "G.g........g.G",
        "gHHHGGGGGGGGgg"
      ],
      "dead": [
        ".....HHGG.....",
        "..HHH....GGG..",
        ".H..........G.",
        "G.g..o.o...g.G",
        "G.g..o.o...g.G",
        "G.g.dEEEDxDg.G",
        "G.gsdDddEDog.G",
        "gHHHGGGGGGGGgg"
      ]
    }
  },
  "tiny": {
    "width": 10,
    "height": 6,
    "frames": {
      "idle": [
        "...HHGG...",
        ".HH.WY.GG.",
        "G..YwKO..G",
        "G.WYyW...G",
        "G..o.o...G",
        "gHHGGGGGGg"
      ],
      "blink": [
        "...HHGG...",
        ".HH.WY.GG.",
        "G..YKKO..G",
        "G.WYyW...G",
        "G..o.o...G",
        "gHHGGGGGGg"
      ],
      "chirp": [
        "...HHGG...",
        ".HH.WYOGG.",
        "G..YwKK..G",
        "G.WYyWO..G",
        "G..o.o...G",
        "gHHGGGGGGg"
      ],
      "hop": [
        "...HHGG...",
        ".HHYwKOGG.",
        "G.WYyW...G",
        "G..o.o...G",
        "G........G",
        "gHHGGGGGGg"
      ],
      "dead": [
        "...HHGG...",
        ".HH....GG.",
        "G..o.o...G",
        "G..EEDxD.G",
        "G.sdDDDo.G",
        "gHHGGGGGGg"
      ]
    }
  }
}
