// Turns design/sprites.json (the art source) into plugins/context-canary/hooks/sprites.js,
// so the mod imports plain data and reads no files at runtime.
// Usage: node scripts/build-sprites.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const root = new URL('..', import.meta.url)
const source = JSON.parse(readFileSync(new URL('design/sprites.json', root), 'utf8'))
const frames = ['idle', 'blink', 'chirp', 'hop', 'dead']

for (const [name, size] of Object.entries(source.sizes)) {
  for (const frame of frames) {
    const rows = size.frames[frame]
    if (!rows) throw new Error(`${name}: missing frame ${frame}`)
    if (rows.length !== size.height || rows.some((row) => row.length !== size.width)) {
      throw new Error(`${name}/${frame}: expected ${size.width}x${size.height}`)
    }
    for (const char of rows.join('')) {
      if (char !== '.' && !source.palette[char]) throw new Error(`${name}/${frame}: unknown color ${char}`)
    }
  }
}

const sizes = Object.fromEntries(Object.entries(source.sizes).map(([name, size]) =>
  [name, { width: size.width, height: size.height, frames: Object.fromEntries(frames.map((f) => [f, size.frames[f]])) }]))
writeFileSync(new URL('plugins/context-canary/hooks/sprites.js', root),
  '// Generated by scripts/build-sprites.mjs from design/sprites.json. Do not edit by hand.\n' +
  `export const PALETTE = ${JSON.stringify(source.palette, null, 2)}\n\n` +
  `export const SPRITES = ${JSON.stringify(sizes, null, 2)}\n`)
console.log('sprites.js written:', Object.entries(sizes).map(([n, s]) => `${n} ${s.width}x${s.height}`).join(', '))
